// scripts/generate-tr-geo.ts
// 81 il + ilçeleri tek bir TS dosyasında statik olarak üretir.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Kaynak: turkey-neighbourhoods
// npm i -D turkey-neighbourhoods
// Not: sadece build-time kullanıyoruz, runtime'a girmiyor.
import * as tr from "turkey-neighbourhoods";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function slugifyTR(input: string) {
  return input
    .toLowerCase()
    .replace(/ğ/g, "g")
    .replace(/ü/g, "u")
    .replace(/ş/g, "s")
    .replace(/ı/g, "i")
    .replace(/ö/g, "o")
    .replace(/ç/g, "c")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

type District = { id: string; name: string };
type Province = { id: string; code: string; name: string; districts: District[] };

function buildAll(): Province[] {
  const cities = tr.getCities() as { code: string; name: string }[];
  return cities.map((c) => {
    const dists = tr.getDistrictsByCityCode(c.code) as string[]; // ilçeler
    return {
      id: c.code,
      code: c.code,
      name: c.name,
      districts: (dists || []).map((d) => ({
        id: slugifyTR(`${c.code}-${d}`),
        name: d,
      })),
    };
  });
}

function emitTS(provinces: Province[]) {
  // Dosya içeriği (tek statik export)
  const header = `// AUTO-GENERATED FILE. Do not edit by hand.
// Generated by scripts/generate-tr-geo.ts
export type District = { id: string; name: string };
export type Province = { id: string; code: string; name: string; districts: District[] };
export const TR_PROVINCES: Province[] = `;

  const json = JSON.stringify(provinces, null, 2);
  return `${header}${json} as const;\n`;
}

function main() {
  const provinces = buildAll();
  const code = emitTS(provinces);
  const outFile = path.join(__dirname, "..", "src", "data", "tr-geo.generated.ts");

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, code, "utf8");

  console.log(`✅ Generated ${outFile} with ${provinces.length} provinces.`);
}

main();
