// AUTO-GENERATED FILE. Do not edit by hand.
// Generated by scripts/generate-tr-geo.ts
export type District = { id: string; name: string };
export type Province = {
  id: string;
  code: string;
  name: string;
  districts: District[];
};
export const TR_PROVINCES: Province[] = [
  {
    id: "01",
    code: "01",
    name: "Adana",
    districts: [
      {
        id: "01-aladag",
        name: "Aladağ",
      },
      {
        id: "01-ceyhan",
        name: "Ceyhan",
      },
      {
        id: "01-cukurova",
        name: "Çukurova",
      },
      {
        id: "01-feke",
        name: "Feke",
      },
      {
        id: "01-i-mamoglu",
        name: "İmamoğlu",
      },
      {
        id: "01-karaisali",
        name: "Karaisalı",
      },
      {
        id: "01-karatas",
        name: "Karataş",
      },
      {
        id: "01-kozan",
        name: "Kozan",
      },
      {
        id: "01-pozanti",
        name: "Pozantı",
      },
      {
        id: "01-saimbeyli",
        name: "Saimbeyli",
      },
      {
        id: "01-saricam",
        name: "Sarıçam",
      },
      {
        id: "01-seyhan",
        name: "Seyhan",
      },
      {
        id: "01-tufanbeyli",
        name: "Tufanbeyli",
      },
      {
        id: "01-yumurtalik",
        name: "Yumurtalık",
      },
      {
        id: "01-yuregir",
        name: "Yüreğir",
      },
    ],
  },
  {
    id: "02",
    code: "02",
    name: "Adıyaman",
    districts: [
      {
        id: "02-besni",
        name: "Besni",
      },
      {
        id: "02-celikhan",
        name: "Çelikhan",
      },
      {
        id: "02-gerger",
        name: "Gerger",
      },
      {
        id: "02-golbasi",
        name: "Gölbaşı",
      },
      {
        id: "02-kahta",
        name: "Kahta",
      },
      {
        id: "02-merkez",
        name: "Merkez",
      },
      {
        id: "02-samsat",
        name: "Samsat",
      },
      {
        id: "02-sincik",
        name: "Sincik",
      },
      {
        id: "02-tut",
        name: "Tut",
      },
    ],
  },
  {
    id: "03",
    code: "03",
    name: "Afyonkarahisar",
    districts: [
      {
        id: "03-basmakci",
        name: "Başmakçı",
      },
      {
        id: "03-bayat",
        name: "Bayat",
      },
      {
        id: "03-bolvadin",
        name: "Bolvadin",
      },
      {
        id: "03-cay",
        name: "Çay",
      },
      {
        id: "03-cobanlar",
        name: "Çobanlar",
      },
      {
        id: "03-dazkiri",
        name: "Dazkırı",
      },
      {
        id: "03-dinar",
        name: "Dinar",
      },
      {
        id: "03-emirdag",
        name: "Emirdağ",
      },
      {
        id: "03-evciler",
        name: "Evciler",
      },
      {
        id: "03-hocalar",
        name: "Hocalar",
      },
      {
        id: "03-i-hsaniye",
        name: "İhsaniye",
      },
      {
        id: "03-i-scehisar",
        name: "İscehisar",
      },
      {
        id: "03-kiziloren",
        name: "Kızılören",
      },
      {
        id: "03-merkez",
        name: "Merkez",
      },
      {
        id: "03-sandikli",
        name: "Sandıklı",
      },
      {
        id: "03-sinanpasa",
        name: "Sinanpaşa",
      },
      {
        id: "03-sultandagi",
        name: "Sultandağı",
      },
      {
        id: "03-suhut",
        name: "Şuhut",
      },
    ],
  },
  {
    id: "04",
    code: "04",
    name: "Ağrı",
    districts: [
      {
        id: "04-diyadin",
        name: "Diyadin",
      },
      {
        id: "04-dogubayazit",
        name: "Doğubayazıt",
      },
      {
        id: "04-eleskirt",
        name: "Eleşkirt",
      },
      {
        id: "04-hamur",
        name: "Hamur",
      },
      {
        id: "04-merkez",
        name: "Merkez",
      },
      {
        id: "04-patnos",
        name: "Patnos",
      },
      {
        id: "04-taslicay",
        name: "Taşlıçay",
      },
      {
        id: "04-tutak",
        name: "Tutak",
      },
    ],
  },
  {
    id: "68",
    code: "68",
    name: "Aksaray",
    districts: [
      {
        id: "68-agacoren",
        name: "Ağaçören",
      },
      {
        id: "68-eskil",
        name: "Eskil",
      },
      {
        id: "68-gulagac",
        name: "Gülağaç",
      },
      {
        id: "68-guzelyurt",
        name: "Güzelyurt",
      },
      {
        id: "68-merkez",
        name: "Merkez",
      },
      {
        id: "68-ortakoy",
        name: "Ortaköy",
      },
      {
        id: "68-sariyahsi",
        name: "Sarıyahşi",
      },
      {
        id: "68-sultanhani",
        name: "Sultanhanı",
      },
    ],
  },
  {
    id: "05",
    code: "05",
    name: "Amasya",
    districts: [
      {
        id: "05-goynucek",
        name: "Göynücek",
      },
      {
        id: "05-gumushacikoy",
        name: "Gümüşhacıköy",
      },
      {
        id: "05-hamamozu",
        name: "Hamamözü",
      },
      {
        id: "05-merkez",
        name: "Merkez",
      },
      {
        id: "05-merzifon",
        name: "Merzifon",
      },
      {
        id: "05-suluova",
        name: "Suluova",
      },
      {
        id: "05-tasova",
        name: "Taşova",
      },
    ],
  },
  {
    id: "06",
    code: "06",
    name: "Ankara",
    districts: [
      {
        id: "06-akyurt",
        name: "Akyurt",
      },
      {
        id: "06-altindag",
        name: "Altındağ",
      },
      {
        id: "06-ayas",
        name: "Ayaş",
      },
      {
        id: "06-bala",
        name: "Bala",
      },
      {
        id: "06-beypazari",
        name: "Beypazarı",
      },
      {
        id: "06-camlidere",
        name: "Çamlıdere",
      },
      {
        id: "06-cankaya",
        name: "Çankaya",
      },
      {
        id: "06-cubuk",
        name: "Çubuk",
      },
      {
        id: "06-elmadag",
        name: "Elmadağ",
      },
      {
        id: "06-etimesgut",
        name: "Etimesgut",
      },
      {
        id: "06-evren",
        name: "Evren",
      },
      {
        id: "06-golbasi",
        name: "Gölbaşı",
      },
      {
        id: "06-gudul",
        name: "Güdül",
      },
      {
        id: "06-haymana",
        name: "Haymana",
      },
      {
        id: "06-kahramankazan",
        name: "Kahramankazan",
      },
      {
        id: "06-kalecik",
        name: "Kalecik",
      },
      {
        id: "06-kecioren",
        name: "Keçiören",
      },
      {
        id: "06-kizilcahamam",
        name: "Kızılcahamam",
      },
      {
        id: "06-mamak",
        name: "Mamak",
      },
      {
        id: "06-nallihan",
        name: "Nallıhan",
      },
      {
        id: "06-polatli",
        name: "Polatlı",
      },
      {
        id: "06-pursaklar",
        name: "Pursaklar",
      },
      {
        id: "06-sincan",
        name: "Sincan",
      },
      {
        id: "06-sereflikochisar",
        name: "Şereflikoçhisar",
      },
      {
        id: "06-yenimahalle",
        name: "Yenimahalle",
      },
    ],
  },
  {
    id: "07",
    code: "07",
    name: "Antalya",
    districts: [
      {
        id: "07-akseki",
        name: "Akseki",
      },
      {
        id: "07-aksu",
        name: "Aksu",
      },
      {
        id: "07-alanya",
        name: "Alanya",
      },
      {
        id: "07-demre",
        name: "Demre",
      },
      {
        id: "07-dosemealti",
        name: "Döşemealtı",
      },
      {
        id: "07-elmali",
        name: "Elmalı",
      },
      {
        id: "07-finike",
        name: "Finike",
      },
      {
        id: "07-gazipasa",
        name: "Gazipaşa",
      },
      {
        id: "07-gundogmus",
        name: "Gündoğmuş",
      },
      {
        id: "07-i-bradi",
        name: "İbradı",
      },
      {
        id: "07-kas",
        name: "Kaş",
      },
      {
        id: "07-kemer",
        name: "Kemer",
      },
      {
        id: "07-kepez",
        name: "Kepez",
      },
      {
        id: "07-konyaalti",
        name: "Konyaaltı",
      },
      {
        id: "07-korkuteli",
        name: "Korkuteli",
      },
      {
        id: "07-kumluca",
        name: "Kumluca",
      },
      {
        id: "07-manavgat",
        name: "Manavgat",
      },
      {
        id: "07-muratpasa",
        name: "Muratpaşa",
      },
      {
        id: "07-serik",
        name: "Serik",
      },
    ],
  },
  {
    id: "75",
    code: "75",
    name: "Ardahan",
    districts: [
      {
        id: "75-cildir",
        name: "Çıldır",
      },
      {
        id: "75-damal",
        name: "Damal",
      },
      {
        id: "75-gole",
        name: "Göle",
      },
      {
        id: "75-hanak",
        name: "Hanak",
      },
      {
        id: "75-merkez",
        name: "Merkez",
      },
      {
        id: "75-posof",
        name: "Posof",
      },
    ],
  },
  {
    id: "08",
    code: "08",
    name: "Artvin",
    districts: [
      {
        id: "08-ardanuc",
        name: "Ardanuç",
      },
      {
        id: "08-arhavi",
        name: "Arhavi",
      },
      {
        id: "08-borcka",
        name: "Borçka",
      },
      {
        id: "08-hopa",
        name: "Hopa",
      },
      {
        id: "08-kemalpasa",
        name: "Kemalpaşa",
      },
      {
        id: "08-merkez",
        name: "Merkez",
      },
      {
        id: "08-murgul",
        name: "Murgul",
      },
      {
        id: "08-savsat",
        name: "Şavşat",
      },
      {
        id: "08-yusufeli",
        name: "Yusufeli",
      },
    ],
  },
  {
    id: "09",
    code: "09",
    name: "Aydın",
    districts: [
      {
        id: "09-bozdogan",
        name: "Bozdoğan",
      },
      {
        id: "09-buharkent",
        name: "Buharkent",
      },
      {
        id: "09-cine",
        name: "Çine",
      },
      {
        id: "09-didim",
        name: "Didim",
      },
      {
        id: "09-efeler",
        name: "Efeler",
      },
      {
        id: "09-germencik",
        name: "Germencik",
      },
      {
        id: "09-i-ncirliova",
        name: "İncirliova",
      },
      {
        id: "09-karacasu",
        name: "Karacasu",
      },
      {
        id: "09-karpuzlu",
        name: "Karpuzlu",
      },
      {
        id: "09-kocarli",
        name: "Koçarlı",
      },
      {
        id: "09-kosk",
        name: "Köşk",
      },
      {
        id: "09-kusadasi",
        name: "Kuşadası",
      },
      {
        id: "09-kuyucak",
        name: "Kuyucak",
      },
      {
        id: "09-nazilli",
        name: "Nazilli",
      },
      {
        id: "09-soke",
        name: "Söke",
      },
      {
        id: "09-sultanhisar",
        name: "Sultanhisar",
      },
      {
        id: "09-yenipazar",
        name: "Yenipazar",
      },
    ],
  },
  {
    id: "10",
    code: "10",
    name: "Balıkesir",
    districts: [
      {
        id: "10-altieylul",
        name: "Altıeylül",
      },
      {
        id: "10-ayvalik",
        name: "Ayvalık",
      },
      {
        id: "10-balya",
        name: "Balya",
      },
      {
        id: "10-bandirma",
        name: "Bandırma",
      },
      {
        id: "10-bigadic",
        name: "Bigadiç",
      },
      {
        id: "10-burhaniye",
        name: "Burhaniye",
      },
      {
        id: "10-dursunbey",
        name: "Dursunbey",
      },
      {
        id: "10-edremit",
        name: "Edremit",
      },
      {
        id: "10-erdek",
        name: "Erdek",
      },
      {
        id: "10-gomec",
        name: "Gömeç",
      },
      {
        id: "10-gonen",
        name: "Gönen",
      },
      {
        id: "10-havran",
        name: "Havran",
      },
      {
        id: "10-i-vrindi",
        name: "İvrindi",
      },
      {
        id: "10-karesi",
        name: "Karesi",
      },
      {
        id: "10-kepsut",
        name: "Kepsut",
      },
      {
        id: "10-manyas",
        name: "Manyas",
      },
      {
        id: "10-marmara",
        name: "Marmara",
      },
      {
        id: "10-savastepe",
        name: "Savaştepe",
      },
      {
        id: "10-sindirgi",
        name: "Sındırgı",
      },
      {
        id: "10-susurluk",
        name: "Susurluk",
      },
    ],
  },
  {
    id: "74",
    code: "74",
    name: "Bartın",
    districts: [
      {
        id: "74-amasra",
        name: "Amasra",
      },
      {
        id: "74-kurucasile",
        name: "Kurucaşile",
      },
      {
        id: "74-merkez",
        name: "Merkez",
      },
      {
        id: "74-ulus",
        name: "Ulus",
      },
    ],
  },
  {
    id: "72",
    code: "72",
    name: "Batman",
    districts: [
      {
        id: "72-besiri",
        name: "Beşiri",
      },
      {
        id: "72-gercus",
        name: "Gercüş",
      },
      {
        id: "72-hasankeyf",
        name: "Hasankeyf",
      },
      {
        id: "72-kozluk",
        name: "Kozluk",
      },
      {
        id: "72-merkez",
        name: "Merkez",
      },
      {
        id: "72-sason",
        name: "Sason",
      },
    ],
  },
  {
    id: "69",
    code: "69",
    name: "Bayburt",
    districts: [
      {
        id: "69-aydintepe",
        name: "Aydıntepe",
      },
      {
        id: "69-demirozu",
        name: "Demirözü",
      },
      {
        id: "69-merkez",
        name: "Merkez",
      },
    ],
  },
  {
    id: "11",
    code: "11",
    name: "Bilecik",
    districts: [
      {
        id: "11-bozuyuk",
        name: "Bozüyük",
      },
      {
        id: "11-golpazari",
        name: "Gölpazarı",
      },
      {
        id: "11-i-nhisar",
        name: "İnhisar",
      },
      {
        id: "11-merkez",
        name: "Merkez",
      },
      {
        id: "11-osmaneli",
        name: "Osmaneli",
      },
      {
        id: "11-pazaryeri",
        name: "Pazaryeri",
      },
      {
        id: "11-sogut",
        name: "Söğüt",
      },
      {
        id: "11-yenipazar",
        name: "Yenipazar",
      },
    ],
  },
  {
    id: "12",
    code: "12",
    name: "Bingöl",
    districts: [
      {
        id: "12-adakli",
        name: "Adaklı",
      },
      {
        id: "12-genc",
        name: "Genç",
      },
      {
        id: "12-karliova",
        name: "Karlıova",
      },
      {
        id: "12-kigi",
        name: "Kiğı",
      },
      {
        id: "12-merkez",
        name: "Merkez",
      },
      {
        id: "12-solhan",
        name: "Solhan",
      },
      {
        id: "12-yayladere",
        name: "Yayladere",
      },
      {
        id: "12-yedisu",
        name: "Yedisu",
      },
    ],
  },
  {
    id: "13",
    code: "13",
    name: "Bitlis",
    districts: [
      {
        id: "13-adilcevaz",
        name: "Adilcevaz",
      },
      {
        id: "13-ahlat",
        name: "Ahlat",
      },
      {
        id: "13-guroymak",
        name: "Güroymak",
      },
      {
        id: "13-hizan",
        name: "Hizan",
      },
      {
        id: "13-merkez",
        name: "Merkez",
      },
      {
        id: "13-mutki",
        name: "Mutki",
      },
      {
        id: "13-tatvan",
        name: "Tatvan",
      },
    ],
  },
  {
    id: "14",
    code: "14",
    name: "Bolu",
    districts: [
      {
        id: "14-dortdivan",
        name: "Dörtdivan",
      },
      {
        id: "14-gerede",
        name: "Gerede",
      },
      {
        id: "14-goynuk",
        name: "Göynük",
      },
      {
        id: "14-kibriscik",
        name: "Kıbrıscık",
      },
      {
        id: "14-mengen",
        name: "Mengen",
      },
      {
        id: "14-merkez",
        name: "Merkez",
      },
      {
        id: "14-mudurnu",
        name: "Mudurnu",
      },
      {
        id: "14-seben",
        name: "Seben",
      },
      {
        id: "14-yenicaga",
        name: "Yeniçağa",
      },
    ],
  },
  {
    id: "15",
    code: "15",
    name: "Burdur",
    districts: [
      {
        id: "15-aglasun",
        name: "Ağlasun",
      },
      {
        id: "15-altinyayla",
        name: "Altınyayla",
      },
      {
        id: "15-bucak",
        name: "Bucak",
      },
      {
        id: "15-cavdir",
        name: "Çavdır",
      },
      {
        id: "15-celtikci",
        name: "Çeltikçi",
      },
      {
        id: "15-golhisar",
        name: "Gölhisar",
      },
      {
        id: "15-karamanli",
        name: "Karamanlı",
      },
      {
        id: "15-kemer",
        name: "Kemer",
      },
      {
        id: "15-merkez",
        name: "Merkez",
      },
      {
        id: "15-tefenni",
        name: "Tefenni",
      },
      {
        id: "15-yesilova",
        name: "Yeşilova",
      },
    ],
  },
  {
    id: "16",
    code: "16",
    name: "Bursa",
    districts: [
      {
        id: "16-buyukorhan",
        name: "Büyükorhan",
      },
      {
        id: "16-gemlik",
        name: "Gemlik",
      },
      {
        id: "16-gursu",
        name: "Gürsu",
      },
      {
        id: "16-harmancik",
        name: "Harmancık",
      },
      {
        id: "16-i-negol",
        name: "İnegöl",
      },
      {
        id: "16-i-znik",
        name: "İznik",
      },
      {
        id: "16-karacabey",
        name: "Karacabey",
      },
      {
        id: "16-keles",
        name: "Keles",
      },
      {
        id: "16-kestel",
        name: "Kestel",
      },
      {
        id: "16-mudanya",
        name: "Mudanya",
      },
      {
        id: "16-mustafakemalpasa",
        name: "Mustafakemalpaşa",
      },
      {
        id: "16-nilufer",
        name: "Nilüfer",
      },
      {
        id: "16-orhaneli",
        name: "Orhaneli",
      },
      {
        id: "16-orhangazi",
        name: "Orhangazi",
      },
      {
        id: "16-osmangazi",
        name: "Osmangazi",
      },
      {
        id: "16-yenisehir",
        name: "Yenişehir",
      },
      {
        id: "16-yildirim",
        name: "Yıldırım",
      },
    ],
  },
  {
    id: "17",
    code: "17",
    name: "Çanakkale",
    districts: [
      {
        id: "17-ayvacik",
        name: "Ayvacık",
      },
      {
        id: "17-bayramic",
        name: "Bayramiç",
      },
      {
        id: "17-biga",
        name: "Biga",
      },
      {
        id: "17-bozcaada",
        name: "Bozcaada",
      },
      {
        id: "17-can",
        name: "Çan",
      },
      {
        id: "17-eceabat",
        name: "Eceabat",
      },
      {
        id: "17-ezine",
        name: "Ezine",
      },
      {
        id: "17-gelibolu",
        name: "Gelibolu",
      },
      {
        id: "17-gokceada",
        name: "Gökçeada",
      },
      {
        id: "17-lapseki",
        name: "Lapseki",
      },
      {
        id: "17-merkez",
        name: "Merkez",
      },
      {
        id: "17-yenice",
        name: "Yenice",
      },
    ],
  },
  {
    id: "18",
    code: "18",
    name: "Çankırı",
    districts: [
      {
        id: "18-atkaracalar",
        name: "Atkaracalar",
      },
      {
        id: "18-bayramoren",
        name: "Bayramören",
      },
      {
        id: "18-cerkes",
        name: "Çerkeş",
      },
      {
        id: "18-eldivan",
        name: "Eldivan",
      },
      {
        id: "18-ilgaz",
        name: "Ilgaz",
      },
      {
        id: "18-kizilirmak",
        name: "Kızılırmak",
      },
      {
        id: "18-korgun",
        name: "Korgun",
      },
      {
        id: "18-kursunlu",
        name: "Kurşunlu",
      },
      {
        id: "18-merkez",
        name: "Merkez",
      },
      {
        id: "18-orta",
        name: "Orta",
      },
      {
        id: "18-sabanozu",
        name: "Şabanözü",
      },
      {
        id: "18-yaprakli",
        name: "Yapraklı",
      },
    ],
  },
  {
    id: "19",
    code: "19",
    name: "Çorum",
    districts: [
      {
        id: "19-alaca",
        name: "Alaca",
      },
      {
        id: "19-bayat",
        name: "Bayat",
      },
      {
        id: "19-bogazkale",
        name: "Boğazkale",
      },
      {
        id: "19-dodurga",
        name: "Dodurga",
      },
      {
        id: "19-i-skilip",
        name: "İskilip",
      },
      {
        id: "19-kargi",
        name: "Kargı",
      },
      {
        id: "19-lacin",
        name: "Laçin",
      },
      {
        id: "19-mecitozu",
        name: "Mecitözü",
      },
      {
        id: "19-merkez",
        name: "Merkez",
      },
      {
        id: "19-oguzlar",
        name: "Oğuzlar",
      },
      {
        id: "19-ortakoy",
        name: "Ortaköy",
      },
      {
        id: "19-osmancik",
        name: "Osmancık",
      },
      {
        id: "19-sungurlu",
        name: "Sungurlu",
      },
      {
        id: "19-ugurludag",
        name: "Uğurludağ",
      },
    ],
  },
  {
    id: "20",
    code: "20",
    name: "Denizli",
    districts: [
      {
        id: "20-acipayam",
        name: "Acıpayam",
      },
      {
        id: "20-babadag",
        name: "Babadağ",
      },
      {
        id: "20-baklan",
        name: "Baklan",
      },
      {
        id: "20-bekilli",
        name: "Bekilli",
      },
      {
        id: "20-beyagac",
        name: "Beyağaç",
      },
      {
        id: "20-bozkurt",
        name: "Bozkurt",
      },
      {
        id: "20-buldan",
        name: "Buldan",
      },
      {
        id: "20-cal",
        name: "Çal",
      },
      {
        id: "20-cameli",
        name: "Çameli",
      },
      {
        id: "20-cardak",
        name: "Çardak",
      },
      {
        id: "20-civril",
        name: "Çivril",
      },
      {
        id: "20-guney",
        name: "Güney",
      },
      {
        id: "20-honaz",
        name: "Honaz",
      },
      {
        id: "20-kale",
        name: "Kale",
      },
      {
        id: "20-merkezefendi",
        name: "Merkezefendi",
      },
      {
        id: "20-pamukkale",
        name: "Pamukkale",
      },
      {
        id: "20-saraykoy",
        name: "Sarayköy",
      },
      {
        id: "20-serinhisar",
        name: "Serinhisar",
      },
      {
        id: "20-tavas",
        name: "Tavas",
      },
    ],
  },
  {
    id: "21",
    code: "21",
    name: "Diyarbakır",
    districts: [
      {
        id: "21-baglar",
        name: "Bağlar",
      },
      {
        id: "21-bismil",
        name: "Bismil",
      },
      {
        id: "21-cermik",
        name: "Çermik",
      },
      {
        id: "21-cinar",
        name: "Çınar",
      },
      {
        id: "21-cungus",
        name: "Çüngüş",
      },
      {
        id: "21-dicle",
        name: "Dicle",
      },
      {
        id: "21-egil",
        name: "Eğil",
      },
      {
        id: "21-ergani",
        name: "Ergani",
      },
      {
        id: "21-hani",
        name: "Hani",
      },
      {
        id: "21-hazro",
        name: "Hazro",
      },
      {
        id: "21-kayapinar",
        name: "Kayapınar",
      },
      {
        id: "21-kocakoy",
        name: "Kocaköy",
      },
      {
        id: "21-kulp",
        name: "Kulp",
      },
      {
        id: "21-lice",
        name: "Lice",
      },
      {
        id: "21-silvan",
        name: "Silvan",
      },
      {
        id: "21-sur",
        name: "Sur",
      },
      {
        id: "21-yenisehir",
        name: "Yenişehir",
      },
    ],
  },
  {
    id: "81",
    code: "81",
    name: "Düzce",
    districts: [
      {
        id: "81-akcakoca",
        name: "Akçakoca",
      },
      {
        id: "81-cumayeri",
        name: "Cumayeri",
      },
      {
        id: "81-cilimli",
        name: "Çilimli",
      },
      {
        id: "81-golyaka",
        name: "Gölyaka",
      },
      {
        id: "81-gumusova",
        name: "Gümüşova",
      },
      {
        id: "81-kaynasli",
        name: "Kaynaşlı",
      },
      {
        id: "81-merkez",
        name: "Merkez",
      },
      {
        id: "81-yigilca",
        name: "Yığılca",
      },
    ],
  },
  {
    id: "22",
    code: "22",
    name: "Edirne",
    districts: [
      {
        id: "22-enez",
        name: "Enez",
      },
      {
        id: "22-havsa",
        name: "Havsa",
      },
      {
        id: "22-i-psala",
        name: "İpsala",
      },
      {
        id: "22-kesan",
        name: "Keşan",
      },
      {
        id: "22-lalapasa",
        name: "Lalapaşa",
      },
      {
        id: "22-meric",
        name: "Meriç",
      },
      {
        id: "22-merkez",
        name: "Merkez",
      },
      {
        id: "22-suloglu",
        name: "Süloğlu",
      },
      {
        id: "22-uzunkopru",
        name: "Uzunköprü",
      },
    ],
  },
  {
    id: "23",
    code: "23",
    name: "Elazığ",
    districts: [
      {
        id: "23-agin",
        name: "Ağın",
      },
      {
        id: "23-alacakaya",
        name: "Alacakaya",
      },
      {
        id: "23-aricak",
        name: "Arıcak",
      },
      {
        id: "23-baskil",
        name: "Baskil",
      },
      {
        id: "23-karakocan",
        name: "Karakoçan",
      },
      {
        id: "23-keban",
        name: "Keban",
      },
      {
        id: "23-kovancilar",
        name: "Kovancılar",
      },
      {
        id: "23-maden",
        name: "Maden",
      },
      {
        id: "23-merkez",
        name: "Merkez",
      },
      {
        id: "23-palu",
        name: "Palu",
      },
      {
        id: "23-sivrice",
        name: "Sivrice",
      },
    ],
  },
  {
    id: "24",
    code: "24",
    name: "Erzincan",
    districts: [
      {
        id: "24-cayirli",
        name: "Çayırlı",
      },
      {
        id: "24-i-lic",
        name: "İliç",
      },
      {
        id: "24-kemah",
        name: "Kemah",
      },
      {
        id: "24-kemaliye",
        name: "Kemaliye",
      },
      {
        id: "24-merkez",
        name: "Merkez",
      },
      {
        id: "24-otlukbeli",
        name: "Otlukbeli",
      },
      {
        id: "24-refahiye",
        name: "Refahiye",
      },
      {
        id: "24-tercan",
        name: "Tercan",
      },
      {
        id: "24-uzumlu",
        name: "Üzümlü",
      },
    ],
  },
  {
    id: "25",
    code: "25",
    name: "Erzurum",
    districts: [
      {
        id: "25-askale",
        name: "Aşkale",
      },
      {
        id: "25-aziziye",
        name: "Aziziye",
      },
      {
        id: "25-cat",
        name: "Çat",
      },
      {
        id: "25-hinis",
        name: "Hınıs",
      },
      {
        id: "25-horasan",
        name: "Horasan",
      },
      {
        id: "25-i-spir",
        name: "İspir",
      },
      {
        id: "25-karacoban",
        name: "Karaçoban",
      },
      {
        id: "25-karayazi",
        name: "Karayazı",
      },
      {
        id: "25-koprukoy",
        name: "Köprüköy",
      },
      {
        id: "25-narman",
        name: "Narman",
      },
      {
        id: "25-oltu",
        name: "Oltu",
      },
      {
        id: "25-olur",
        name: "Olur",
      },
      {
        id: "25-palandoken",
        name: "Palandöken",
      },
      {
        id: "25-pasinler",
        name: "Pasinler",
      },
      {
        id: "25-pazaryolu",
        name: "Pazaryolu",
      },
      {
        id: "25-senkaya",
        name: "Şenkaya",
      },
      {
        id: "25-tekman",
        name: "Tekman",
      },
      {
        id: "25-tortum",
        name: "Tortum",
      },
      {
        id: "25-uzundere",
        name: "Uzundere",
      },
      {
        id: "25-yakutiye",
        name: "Yakutiye",
      },
    ],
  },
  {
    id: "26",
    code: "26",
    name: "Eskişehir",
    districts: [
      {
        id: "26-alpu",
        name: "Alpu",
      },
      {
        id: "26-beylikova",
        name: "Beylikova",
      },
      {
        id: "26-cifteler",
        name: "Çifteler",
      },
      {
        id: "26-gunyuzu",
        name: "Günyüzü",
      },
      {
        id: "26-han",
        name: "Han",
      },
      {
        id: "26-i-nonu",
        name: "İnönü",
      },
      {
        id: "26-mahmudiye",
        name: "Mahmudiye",
      },
      {
        id: "26-mihalgazi",
        name: "Mihalgazi",
      },
      {
        id: "26-mihaliccik",
        name: "Mihalıççık",
      },
      {
        id: "26-odunpazari",
        name: "Odunpazarı",
      },
      {
        id: "26-saricakaya",
        name: "Sarıcakaya",
      },
      {
        id: "26-seyitgazi",
        name: "Seyitgazi",
      },
      {
        id: "26-sivrihisar",
        name: "Sivrihisar",
      },
      {
        id: "26-tepebasi",
        name: "Tepebaşı",
      },
    ],
  },
  {
    id: "27",
    code: "27",
    name: "Gaziantep",
    districts: [
      {
        id: "27-araban",
        name: "Araban",
      },
      {
        id: "27-i-slahiye",
        name: "İslahiye",
      },
      {
        id: "27-karkamis",
        name: "Karkamış",
      },
      {
        id: "27-nizip",
        name: "Nizip",
      },
      {
        id: "27-nurdagi",
        name: "Nurdağı",
      },
      {
        id: "27-oguzeli",
        name: "Oğuzeli",
      },
      {
        id: "27-sahinbey",
        name: "Şahinbey",
      },
      {
        id: "27-sehitkamil",
        name: "Şehitkamil",
      },
      {
        id: "27-yavuzeli",
        name: "Yavuzeli",
      },
    ],
  },
  {
    id: "28",
    code: "28",
    name: "Giresun",
    districts: [
      {
        id: "28-alucra",
        name: "Alucra",
      },
      {
        id: "28-bulancak",
        name: "Bulancak",
      },
      {
        id: "28-camoluk",
        name: "Çamoluk",
      },
      {
        id: "28-canakci",
        name: "Çanakçı",
      },
      {
        id: "28-dereli",
        name: "Dereli",
      },
      {
        id: "28-dogankent",
        name: "Doğankent",
      },
      {
        id: "28-espiye",
        name: "Espiye",
      },
      {
        id: "28-eynesil",
        name: "Eynesil",
      },
      {
        id: "28-gorele",
        name: "Görele",
      },
      {
        id: "28-guce",
        name: "Güce",
      },
      {
        id: "28-kesap",
        name: "Keşap",
      },
      {
        id: "28-merkez",
        name: "Merkez",
      },
      {
        id: "28-piraziz",
        name: "Piraziz",
      },
      {
        id: "28-sebinkarahisar",
        name: "Şebinkarahisar",
      },
      {
        id: "28-tirebolu",
        name: "Tirebolu",
      },
      {
        id: "28-yaglidere",
        name: "Yağlıdere",
      },
    ],
  },
  {
    id: "29",
    code: "29",
    name: "Gümüşhane",
    districts: [
      {
        id: "29-kelkit",
        name: "Kelkit",
      },
      {
        id: "29-kose",
        name: "Köse",
      },
      {
        id: "29-kurtun",
        name: "Kürtün",
      },
      {
        id: "29-merkez",
        name: "Merkez",
      },
      {
        id: "29-siran",
        name: "Şiran",
      },
      {
        id: "29-torul",
        name: "Torul",
      },
    ],
  },
  {
    id: "30",
    code: "30",
    name: "Hakkari",
    districts: [
      {
        id: "30-cukurca",
        name: "Çukurca",
      },
      {
        id: "30-derecik",
        name: "Derecik",
      },
      {
        id: "30-merkez",
        name: "Merkez",
      },
      {
        id: "30-semdinli",
        name: "Şemdinli",
      },
      {
        id: "30-yuksekova",
        name: "Yüksekova",
      },
    ],
  },
  {
    id: "31",
    code: "31",
    name: "Hatay",
    districts: [
      {
        id: "31-altinozu",
        name: "Altınözü",
      },
      {
        id: "31-antakya",
        name: "Antakya",
      },
      {
        id: "31-arsuz",
        name: "Arsuz",
      },
      {
        id: "31-belen",
        name: "Belen",
      },
      {
        id: "31-defne",
        name: "Defne",
      },
      {
        id: "31-dortyol",
        name: "Dörtyol",
      },
      {
        id: "31-erzin",
        name: "Erzin",
      },
      {
        id: "31-hassa",
        name: "Hassa",
      },
      {
        id: "31-i-skenderun",
        name: "İskenderun",
      },
      {
        id: "31-kirikhan",
        name: "Kırıkhan",
      },
      {
        id: "31-kumlu",
        name: "Kumlu",
      },
      {
        id: "31-payas",
        name: "Payas",
      },
      {
        id: "31-reyhanli",
        name: "Reyhanlı",
      },
      {
        id: "31-samandag",
        name: "Samandağ",
      },
      {
        id: "31-yayladagi",
        name: "Yayladağı",
      },
    ],
  },
  {
    id: "76",
    code: "76",
    name: "Iğdır",
    districts: [
      {
        id: "76-aralik",
        name: "Aralık",
      },
      {
        id: "76-karakoyunlu",
        name: "Karakoyunlu",
      },
      {
        id: "76-merkez",
        name: "Merkez",
      },
      {
        id: "76-tuzluca",
        name: "Tuzluca",
      },
    ],
  },
  {
    id: "32",
    code: "32",
    name: "Isparta",
    districts: [
      {
        id: "32-aksu",
        name: "Aksu",
      },
      {
        id: "32-atabey",
        name: "Atabey",
      },
      {
        id: "32-egirdir",
        name: "Eğirdir",
      },
      {
        id: "32-gelendost",
        name: "Gelendost",
      },
      {
        id: "32-gonen",
        name: "Gönen",
      },
      {
        id: "32-keciborlu",
        name: "Keçiborlu",
      },
      {
        id: "32-merkez",
        name: "Merkez",
      },
      {
        id: "32-senirkent",
        name: "Senirkent",
      },
      {
        id: "32-sutculer",
        name: "Sütçüler",
      },
      {
        id: "32-sarkikaraagac",
        name: "Şarkikaraağaç",
      },
      {
        id: "32-uluborlu",
        name: "Uluborlu",
      },
      {
        id: "32-yalvac",
        name: "Yalvaç",
      },
      {
        id: "32-yenisarbademli",
        name: "Yenişarbademli",
      },
    ],
  },
  {
    id: "34",
    code: "34",
    name: "İstanbul",
    districts: [
      {
        id: "34-adalar",
        name: "Adalar",
      },
      {
        id: "34-arnavutkoy",
        name: "Arnavutköy",
      },
      {
        id: "34-atasehir",
        name: "Ataşehir",
      },
      {
        id: "34-avcilar",
        name: "Avcılar",
      },
      {
        id: "34-bagcilar",
        name: "Bağcılar",
      },
      {
        id: "34-bahcelievler",
        name: "Bahçelievler",
      },
      {
        id: "34-bakirkoy",
        name: "Bakırköy",
      },
      {
        id: "34-basaksehir",
        name: "Başakşehir",
      },
      {
        id: "34-bayrampasa",
        name: "Bayrampaşa",
      },
      {
        id: "34-besiktas",
        name: "Beşiktaş",
      },
      {
        id: "34-beykoz",
        name: "Beykoz",
      },
      {
        id: "34-beylikduzu",
        name: "Beylikdüzü",
      },
      {
        id: "34-beyoglu",
        name: "Beyoğlu",
      },
      {
        id: "34-buyukcekmece",
        name: "Büyükçekmece",
      },
      {
        id: "34-catalca",
        name: "Çatalca",
      },
      {
        id: "34-cekmekoy",
        name: "Çekmeköy",
      },
      {
        id: "34-esenler",
        name: "Esenler",
      },
      {
        id: "34-esenyurt",
        name: "Esenyurt",
      },
      {
        id: "34-eyupsultan",
        name: "Eyüpsultan",
      },
      {
        id: "34-fatih",
        name: "Fatih",
      },
      {
        id: "34-gaziosmanpasa",
        name: "Gaziosmanpaşa",
      },
      {
        id: "34-gungoren",
        name: "Güngören",
      },
      {
        id: "34-kadikoy",
        name: "Kadıköy",
      },
      {
        id: "34-kagithane",
        name: "Kağıthane",
      },
      {
        id: "34-kartal",
        name: "Kartal",
      },
      {
        id: "34-kucukcekmece",
        name: "Küçükçekmece",
      },
      {
        id: "34-maltepe",
        name: "Maltepe",
      },
      {
        id: "34-pendik",
        name: "Pendik",
      },
      {
        id: "34-sancaktepe",
        name: "Sancaktepe",
      },
      {
        id: "34-sariyer",
        name: "Sarıyer",
      },
      {
        id: "34-silivri",
        name: "Silivri",
      },
      {
        id: "34-sultanbeyli",
        name: "Sultanbeyli",
      },
      {
        id: "34-sultangazi",
        name: "Sultangazi",
      },
      {
        id: "34-sile",
        name: "Şile",
      },
      {
        id: "34-sisli",
        name: "Şişli",
      },
      {
        id: "34-tuzla",
        name: "Tuzla",
      },
      {
        id: "34-umraniye",
        name: "Ümraniye",
      },
      {
        id: "34-uskudar",
        name: "Üsküdar",
      },
      {
        id: "34-zeytinburnu",
        name: "Zeytinburnu",
      },
    ],
  },
  {
    id: "35",
    code: "35",
    name: "İzmir",
    districts: [
      {
        id: "35-aliaga",
        name: "Aliağa",
      },
      {
        id: "35-balcova",
        name: "Balçova",
      },
      {
        id: "35-bayindir",
        name: "Bayındır",
      },
      {
        id: "35-bayrakli",
        name: "Bayraklı",
      },
      {
        id: "35-bergama",
        name: "Bergama",
      },
      {
        id: "35-beydag",
        name: "Beydağ",
      },
      {
        id: "35-bornova",
        name: "Bornova",
      },
      {
        id: "35-buca",
        name: "Buca",
      },
      {
        id: "35-cesme",
        name: "Çeşme",
      },
      {
        id: "35-cigli",
        name: "Çiğli",
      },
      {
        id: "35-dikili",
        name: "Dikili",
      },
      {
        id: "35-foca",
        name: "Foça",
      },
      {
        id: "35-gaziemir",
        name: "Gaziemir",
      },
      {
        id: "35-guzelbahce",
        name: "Güzelbahçe",
      },
      {
        id: "35-karabaglar",
        name: "Karabağlar",
      },
      {
        id: "35-karaburun",
        name: "Karaburun",
      },
      {
        id: "35-karsiyaka",
        name: "Karşıyaka",
      },
      {
        id: "35-kemalpasa",
        name: "Kemalpaşa",
      },
      {
        id: "35-kinik",
        name: "Kınık",
      },
      {
        id: "35-kiraz",
        name: "Kiraz",
      },
      {
        id: "35-konak",
        name: "Konak",
      },
      {
        id: "35-menderes",
        name: "Menderes",
      },
      {
        id: "35-menemen",
        name: "Menemen",
      },
      {
        id: "35-narlidere",
        name: "Narlıdere",
      },
      {
        id: "35-odemis",
        name: "Ödemiş",
      },
      {
        id: "35-seferihisar",
        name: "Seferihisar",
      },
      {
        id: "35-selcuk",
        name: "Selçuk",
      },
      {
        id: "35-tire",
        name: "Tire",
      },
      {
        id: "35-torbali",
        name: "Torbalı",
      },
      {
        id: "35-urla",
        name: "Urla",
      },
    ],
  },
  {
    id: "46",
    code: "46",
    name: "Kahramanmaraş",
    districts: [
      {
        id: "46-afsin",
        name: "Afşin",
      },
      {
        id: "46-andirin",
        name: "Andırın",
      },
      {
        id: "46-caglayancerit",
        name: "Çağlayancerit",
      },
      {
        id: "46-dulkadiroglu",
        name: "Dulkadiroğlu",
      },
      {
        id: "46-ekinozu",
        name: "Ekinözü",
      },
      {
        id: "46-elbistan",
        name: "Elbistan",
      },
      {
        id: "46-goksun",
        name: "Göksun",
      },
      {
        id: "46-nurhak",
        name: "Nurhak",
      },
      {
        id: "46-onikisubat",
        name: "Onikişubat",
      },
      {
        id: "46-pazarcik",
        name: "Pazarcık",
      },
      {
        id: "46-turkoglu",
        name: "Türkoğlu",
      },
    ],
  },
  {
    id: "78",
    code: "78",
    name: "Karabük",
    districts: [
      {
        id: "78-eflani",
        name: "Eflani",
      },
      {
        id: "78-eskipazar",
        name: "Eskipazar",
      },
      {
        id: "78-merkez",
        name: "Merkez",
      },
      {
        id: "78-ovacik",
        name: "Ovacık",
      },
      {
        id: "78-safranbolu",
        name: "Safranbolu",
      },
      {
        id: "78-yenice",
        name: "Yenice",
      },
    ],
  },
  {
    id: "70",
    code: "70",
    name: "Karaman",
    districts: [
      {
        id: "70-ayranci",
        name: "Ayrancı",
      },
      {
        id: "70-basyayla",
        name: "Başyayla",
      },
      {
        id: "70-ermenek",
        name: "Ermenek",
      },
      {
        id: "70-kazimkarabekir",
        name: "Kazımkarabekir",
      },
      {
        id: "70-merkez",
        name: "Merkez",
      },
      {
        id: "70-sariveliler",
        name: "Sarıveliler",
      },
    ],
  },
  {
    id: "36",
    code: "36",
    name: "Kars",
    districts: [
      {
        id: "36-akyaka",
        name: "Akyaka",
      },
      {
        id: "36-arpacay",
        name: "Arpaçay",
      },
      {
        id: "36-digor",
        name: "Digor",
      },
      {
        id: "36-kagizman",
        name: "Kağızman",
      },
      {
        id: "36-merkez",
        name: "Merkez",
      },
      {
        id: "36-sarikamis",
        name: "Sarıkamış",
      },
      {
        id: "36-selim",
        name: "Selim",
      },
      {
        id: "36-susuz",
        name: "Susuz",
      },
    ],
  },
  {
    id: "37",
    code: "37",
    name: "Kastamonu",
    districts: [
      {
        id: "37-abana",
        name: "Abana",
      },
      {
        id: "37-agli",
        name: "Ağlı",
      },
      {
        id: "37-arac",
        name: "Araç",
      },
      {
        id: "37-azdavay",
        name: "Azdavay",
      },
      {
        id: "37-bozkurt",
        name: "Bozkurt",
      },
      {
        id: "37-cide",
        name: "Cide",
      },
      {
        id: "37-catalzeytin",
        name: "Çatalzeytin",
      },
      {
        id: "37-daday",
        name: "Daday",
      },
      {
        id: "37-devrekani",
        name: "Devrekani",
      },
      {
        id: "37-doganyurt",
        name: "Doğanyurt",
      },
      {
        id: "37-hanonu",
        name: "Hanönü",
      },
      {
        id: "37-i-hsangazi",
        name: "İhsangazi",
      },
      {
        id: "37-i-nebolu",
        name: "İnebolu",
      },
      {
        id: "37-kure",
        name: "Küre",
      },
      {
        id: "37-merkez",
        name: "Merkez",
      },
      {
        id: "37-pinarbasi",
        name: "Pınarbaşı",
      },
      {
        id: "37-seydiler",
        name: "Seydiler",
      },
      {
        id: "37-senpazar",
        name: "Şenpazar",
      },
      {
        id: "37-taskopru",
        name: "Taşköprü",
      },
      {
        id: "37-tosya",
        name: "Tosya",
      },
    ],
  },
  {
    id: "38",
    code: "38",
    name: "Kayseri",
    districts: [
      {
        id: "38-akkisla",
        name: "Akkışla",
      },
      {
        id: "38-bunyan",
        name: "Bünyan",
      },
      {
        id: "38-develi",
        name: "Develi",
      },
      {
        id: "38-felahiye",
        name: "Felahiye",
      },
      {
        id: "38-hacilar",
        name: "Hacılar",
      },
      {
        id: "38-i-ncesu",
        name: "İncesu",
      },
      {
        id: "38-kocasinan",
        name: "Kocasinan",
      },
      {
        id: "38-melikgazi",
        name: "Melikgazi",
      },
      {
        id: "38-ozvatan",
        name: "Özvatan",
      },
      {
        id: "38-pinarbasi",
        name: "Pınarbaşı",
      },
      {
        id: "38-sarioglan",
        name: "Sarıoğlan",
      },
      {
        id: "38-sariz",
        name: "Sarız",
      },
      {
        id: "38-talas",
        name: "Talas",
      },
      {
        id: "38-tomarza",
        name: "Tomarza",
      },
      {
        id: "38-yahyali",
        name: "Yahyalı",
      },
      {
        id: "38-yesilhisar",
        name: "Yeşilhisar",
      },
    ],
  },
  {
    id: "71",
    code: "71",
    name: "Kırıkkale",
    districts: [
      {
        id: "71-bahsili",
        name: "Bahşılı",
      },
      {
        id: "71-baliseyh",
        name: "Balışeyh",
      },
      {
        id: "71-celebi",
        name: "Çelebi",
      },
      {
        id: "71-delice",
        name: "Delice",
      },
      {
        id: "71-karakecili",
        name: "Karakeçili",
      },
      {
        id: "71-keskin",
        name: "Keskin",
      },
      {
        id: "71-merkez",
        name: "Merkez",
      },
      {
        id: "71-sulakyurt",
        name: "Sulakyurt",
      },
      {
        id: "71-yahsihan",
        name: "Yahşihan",
      },
    ],
  },
  {
    id: "39",
    code: "39",
    name: "Kırklareli",
    districts: [
      {
        id: "39-babaeski",
        name: "Babaeski",
      },
      {
        id: "39-demirkoy",
        name: "Demirköy",
      },
      {
        id: "39-kofcaz",
        name: "Kofçaz",
      },
      {
        id: "39-luleburgaz",
        name: "Lüleburgaz",
      },
      {
        id: "39-merkez",
        name: "Merkez",
      },
      {
        id: "39-pehlivankoy",
        name: "Pehlivanköy",
      },
      {
        id: "39-pinarhisar",
        name: "Pınarhisar",
      },
      {
        id: "39-vize",
        name: "Vize",
      },
    ],
  },
  {
    id: "40",
    code: "40",
    name: "Kırşehir",
    districts: [
      {
        id: "40-akcakent",
        name: "Akçakent",
      },
      {
        id: "40-akpinar",
        name: "Akpınar",
      },
      {
        id: "40-boztepe",
        name: "Boztepe",
      },
      {
        id: "40-cicekdagi",
        name: "Çiçekdağı",
      },
      {
        id: "40-kaman",
        name: "Kaman",
      },
      {
        id: "40-merkez",
        name: "Merkez",
      },
      {
        id: "40-mucur",
        name: "Mucur",
      },
    ],
  },
  {
    id: "79",
    code: "79",
    name: "Kilis",
    districts: [
      {
        id: "79-elbeyli",
        name: "Elbeyli",
      },
      {
        id: "79-merkez",
        name: "Merkez",
      },
      {
        id: "79-musabeyli",
        name: "Musabeyli",
      },
      {
        id: "79-polateli",
        name: "Polateli",
      },
    ],
  },
  {
    id: "41",
    code: "41",
    name: "Kocaeli",
    districts: [
      {
        id: "41-basiskele",
        name: "Başiskele",
      },
      {
        id: "41-cayirova",
        name: "Çayırova",
      },
      {
        id: "41-darica",
        name: "Darıca",
      },
      {
        id: "41-derince",
        name: "Derince",
      },
      {
        id: "41-dilovasi",
        name: "Dilovası",
      },
      {
        id: "41-gebze",
        name: "Gebze",
      },
      {
        id: "41-golcuk",
        name: "Gölcük",
      },
      {
        id: "41-i-zmit",
        name: "İzmit",
      },
      {
        id: "41-kandira",
        name: "Kandıra",
      },
      {
        id: "41-karamursel",
        name: "Karamürsel",
      },
      {
        id: "41-kartepe",
        name: "Kartepe",
      },
      {
        id: "41-korfez",
        name: "Körfez",
      },
    ],
  },
  {
    id: "42",
    code: "42",
    name: "Konya",
    districts: [
      {
        id: "42-ahirli",
        name: "Ahırlı",
      },
      {
        id: "42-akoren",
        name: "Akören",
      },
      {
        id: "42-aksehir",
        name: "Akşehir",
      },
      {
        id: "42-altinekin",
        name: "Altınekin",
      },
      {
        id: "42-beysehir",
        name: "Beyşehir",
      },
      {
        id: "42-bozkir",
        name: "Bozkır",
      },
      {
        id: "42-cihanbeyli",
        name: "Cihanbeyli",
      },
      {
        id: "42-celtik",
        name: "Çeltik",
      },
      {
        id: "42-cumra",
        name: "Çumra",
      },
      {
        id: "42-derbent",
        name: "Derbent",
      },
      {
        id: "42-derebucak",
        name: "Derebucak",
      },
      {
        id: "42-doganhisar",
        name: "Doğanhisar",
      },
      {
        id: "42-emirgazi",
        name: "Emirgazi",
      },
      {
        id: "42-eregli",
        name: "Ereğli",
      },
      {
        id: "42-guneysinir",
        name: "Güneysınır",
      },
      {
        id: "42-hadim",
        name: "Hadim",
      },
      {
        id: "42-halkapinar",
        name: "Halkapınar",
      },
      {
        id: "42-huyuk",
        name: "Hüyük",
      },
      {
        id: "42-ilgin",
        name: "Ilgın",
      },
      {
        id: "42-kadinhani",
        name: "Kadınhanı",
      },
      {
        id: "42-karapinar",
        name: "Karapınar",
      },
      {
        id: "42-karatay",
        name: "Karatay",
      },
      {
        id: "42-kulu",
        name: "Kulu",
      },
      {
        id: "42-meram",
        name: "Meram",
      },
      {
        id: "42-sarayonu",
        name: "Sarayönü",
      },
      {
        id: "42-selcuklu",
        name: "Selçuklu",
      },
      {
        id: "42-seydisehir",
        name: "Seydişehir",
      },
      {
        id: "42-taskent",
        name: "Taşkent",
      },
      {
        id: "42-tuzlukcu",
        name: "Tuzlukçu",
      },
      {
        id: "42-yalihuyuk",
        name: "Yalıhüyük",
      },
      {
        id: "42-yunak",
        name: "Yunak",
      },
    ],
  },
  {
    id: "43",
    code: "43",
    name: "Kütahya",
    districts: [
      {
        id: "43-altintas",
        name: "Altıntaş",
      },
      {
        id: "43-aslanapa",
        name: "Aslanapa",
      },
      {
        id: "43-cavdarhisar",
        name: "Çavdarhisar",
      },
      {
        id: "43-domanic",
        name: "Domaniç",
      },
      {
        id: "43-dumlupinar",
        name: "Dumlupınar",
      },
      {
        id: "43-emet",
        name: "Emet",
      },
      {
        id: "43-gediz",
        name: "Gediz",
      },
      {
        id: "43-hisarcik",
        name: "Hisarcık",
      },
      {
        id: "43-merkez",
        name: "Merkez",
      },
      {
        id: "43-pazarlar",
        name: "Pazarlar",
      },
      {
        id: "43-simav",
        name: "Simav",
      },
      {
        id: "43-saphane",
        name: "Şaphane",
      },
      {
        id: "43-tavsanli",
        name: "Tavşanlı",
      },
    ],
  },
  {
    id: "44",
    code: "44",
    name: "Malatya",
    districts: [
      {
        id: "44-akcadag",
        name: "Akçadağ",
      },
      {
        id: "44-arapgir",
        name: "Arapgir",
      },
      {
        id: "44-arguvan",
        name: "Arguvan",
      },
      {
        id: "44-battalgazi",
        name: "Battalgazi",
      },
      {
        id: "44-darende",
        name: "Darende",
      },
      {
        id: "44-dogansehir",
        name: "Doğanşehir",
      },
      {
        id: "44-doganyol",
        name: "Doğanyol",
      },
      {
        id: "44-hekimhan",
        name: "Hekimhan",
      },
      {
        id: "44-kale",
        name: "Kale",
      },
      {
        id: "44-kuluncak",
        name: "Kuluncak",
      },
      {
        id: "44-puturge",
        name: "Pütürge",
      },
      {
        id: "44-yazihan",
        name: "Yazıhan",
      },
      {
        id: "44-yesilyurt",
        name: "Yeşilyurt",
      },
    ],
  },
  {
    id: "45",
    code: "45",
    name: "Manisa",
    districts: [
      {
        id: "45-ahmetli",
        name: "Ahmetli",
      },
      {
        id: "45-akhisar",
        name: "Akhisar",
      },
      {
        id: "45-alasehir",
        name: "Alaşehir",
      },
      {
        id: "45-demirci",
        name: "Demirci",
      },
      {
        id: "45-golmarmara",
        name: "Gölmarmara",
      },
      {
        id: "45-gordes",
        name: "Gördes",
      },
      {
        id: "45-kirkagac",
        name: "Kırkağaç",
      },
      {
        id: "45-koprubasi",
        name: "Köprübaşı",
      },
      {
        id: "45-kula",
        name: "Kula",
      },
      {
        id: "45-salihli",
        name: "Salihli",
      },
      {
        id: "45-sarigol",
        name: "Sarıgöl",
      },
      {
        id: "45-saruhanli",
        name: "Saruhanlı",
      },
      {
        id: "45-selendi",
        name: "Selendi",
      },
      {
        id: "45-soma",
        name: "Soma",
      },
      {
        id: "45-sehzadeler",
        name: "Şehzadeler",
      },
      {
        id: "45-turgutlu",
        name: "Turgutlu",
      },
      {
        id: "45-yunusemre",
        name: "Yunusemre",
      },
    ],
  },
  {
    id: "47",
    code: "47",
    name: "Mardin",
    districts: [
      {
        id: "47-artuklu",
        name: "Artuklu",
      },
      {
        id: "47-dargecit",
        name: "Dargeçit",
      },
      {
        id: "47-derik",
        name: "Derik",
      },
      {
        id: "47-kiziltepe",
        name: "Kızıltepe",
      },
      {
        id: "47-mazidagi",
        name: "Mazıdağı",
      },
      {
        id: "47-midyat",
        name: "Midyat",
      },
      {
        id: "47-nusaybin",
        name: "Nusaybin",
      },
      {
        id: "47-omerli",
        name: "Ömerli",
      },
      {
        id: "47-savur",
        name: "Savur",
      },
      {
        id: "47-yesilli",
        name: "Yeşilli",
      },
    ],
  },
  {
    id: "33",
    code: "33",
    name: "Mersin",
    districts: [
      {
        id: "33-akdeniz",
        name: "Akdeniz",
      },
      {
        id: "33-anamur",
        name: "Anamur",
      },
      {
        id: "33-aydincik",
        name: "Aydıncık",
      },
      {
        id: "33-bozyazi",
        name: "Bozyazı",
      },
      {
        id: "33-camliyayla",
        name: "Çamlıyayla",
      },
      {
        id: "33-erdemli",
        name: "Erdemli",
      },
      {
        id: "33-gulnar",
        name: "Gülnar",
      },
      {
        id: "33-mezitli",
        name: "Mezitli",
      },
      {
        id: "33-mut",
        name: "Mut",
      },
      {
        id: "33-silifke",
        name: "Silifke",
      },
      {
        id: "33-tarsus",
        name: "Tarsus",
      },
      {
        id: "33-toroslar",
        name: "Toroslar",
      },
      {
        id: "33-yenisehir",
        name: "Yenişehir",
      },
    ],
  },
  {
    id: "48",
    code: "48",
    name: "Muğla",
    districts: [
      {
        id: "48-bodrum",
        name: "Bodrum",
      },
      {
        id: "48-dalaman",
        name: "Dalaman",
      },
      {
        id: "48-datca",
        name: "Datça",
      },
      {
        id: "48-fethiye",
        name: "Fethiye",
      },
      {
        id: "48-kavaklidere",
        name: "Kavaklıdere",
      },
      {
        id: "48-koycegiz",
        name: "Köyceğiz",
      },
      {
        id: "48-marmaris",
        name: "Marmaris",
      },
      {
        id: "48-mentese",
        name: "Menteşe",
      },
      {
        id: "48-milas",
        name: "Milas",
      },
      {
        id: "48-ortaca",
        name: "Ortaca",
      },
      {
        id: "48-seydikemer",
        name: "Seydikemer",
      },
      {
        id: "48-ula",
        name: "Ula",
      },
      {
        id: "48-yatagan",
        name: "Yatağan",
      },
    ],
  },
  {
    id: "49",
    code: "49",
    name: "Muş",
    districts: [
      {
        id: "49-bulanik",
        name: "Bulanık",
      },
      {
        id: "49-haskoy",
        name: "Hasköy",
      },
      {
        id: "49-korkut",
        name: "Korkut",
      },
      {
        id: "49-malazgirt",
        name: "Malazgirt",
      },
      {
        id: "49-merkez",
        name: "Merkez",
      },
      {
        id: "49-varto",
        name: "Varto",
      },
    ],
  },
  {
    id: "50",
    code: "50",
    name: "Nevşehir",
    districts: [
      {
        id: "50-acigol",
        name: "Acıgöl",
      },
      {
        id: "50-avanos",
        name: "Avanos",
      },
      {
        id: "50-derinkuyu",
        name: "Derinkuyu",
      },
      {
        id: "50-gulsehir",
        name: "Gülşehir",
      },
      {
        id: "50-hacibektas",
        name: "Hacıbektaş",
      },
      {
        id: "50-kozakli",
        name: "Kozaklı",
      },
      {
        id: "50-merkez",
        name: "Merkez",
      },
      {
        id: "50-urgup",
        name: "Ürgüp",
      },
    ],
  },
  {
    id: "51",
    code: "51",
    name: "Niğde",
    districts: [
      {
        id: "51-altunhisar",
        name: "Altunhisar",
      },
      {
        id: "51-bor",
        name: "Bor",
      },
      {
        id: "51-camardi",
        name: "Çamardı",
      },
      {
        id: "51-ciftlik",
        name: "Çiftlik",
      },
      {
        id: "51-merkez",
        name: "Merkez",
      },
      {
        id: "51-ulukisla",
        name: "Ulukışla",
      },
    ],
  },
  {
    id: "52",
    code: "52",
    name: "Ordu",
    districts: [
      {
        id: "52-akkus",
        name: "Akkuş",
      },
      {
        id: "52-altinordu",
        name: "Altınordu",
      },
      {
        id: "52-aybasti",
        name: "Aybastı",
      },
      {
        id: "52-camas",
        name: "Çamaş",
      },
      {
        id: "52-catalpinar",
        name: "Çatalpınar",
      },
      {
        id: "52-caybasi",
        name: "Çaybaşı",
      },
      {
        id: "52-fatsa",
        name: "Fatsa",
      },
      {
        id: "52-golkoy",
        name: "Gölköy",
      },
      {
        id: "52-gulyali",
        name: "Gülyalı",
      },
      {
        id: "52-gurgentepe",
        name: "Gürgentepe",
      },
      {
        id: "52-i-kizce",
        name: "İkizce",
      },
      {
        id: "52-kabaduz",
        name: "Kabadüz",
      },
      {
        id: "52-kabatas",
        name: "Kabataş",
      },
      {
        id: "52-korgan",
        name: "Korgan",
      },
      {
        id: "52-kumru",
        name: "Kumru",
      },
      {
        id: "52-mesudiye",
        name: "Mesudiye",
      },
      {
        id: "52-persembe",
        name: "Perşembe",
      },
      {
        id: "52-ulubey",
        name: "Ulubey",
      },
      {
        id: "52-unye",
        name: "Ünye",
      },
    ],
  },
  {
    id: "80",
    code: "80",
    name: "Osmaniye",
    districts: [
      {
        id: "80-bahce",
        name: "Bahçe",
      },
      {
        id: "80-duzici",
        name: "Düziçi",
      },
      {
        id: "80-hasanbeyli",
        name: "Hasanbeyli",
      },
      {
        id: "80-kadirli",
        name: "Kadirli",
      },
      {
        id: "80-merkez",
        name: "Merkez",
      },
      {
        id: "80-sumbas",
        name: "Sumbas",
      },
      {
        id: "80-toprakkale",
        name: "Toprakkale",
      },
    ],
  },
  {
    id: "53",
    code: "53",
    name: "Rize",
    districts: [
      {
        id: "53-ardesen",
        name: "Ardeşen",
      },
      {
        id: "53-camlihemsin",
        name: "Çamlıhemşin",
      },
      {
        id: "53-cayeli",
        name: "Çayeli",
      },
      {
        id: "53-derepazari",
        name: "Derepazarı",
      },
      {
        id: "53-findikli",
        name: "Fındıklı",
      },
      {
        id: "53-guneysu",
        name: "Güneysu",
      },
      {
        id: "53-hemsin",
        name: "Hemşin",
      },
      {
        id: "53-i-kizdere",
        name: "İkizdere",
      },
      {
        id: "53-i-yidere",
        name: "İyidere",
      },
      {
        id: "53-kalkandere",
        name: "Kalkandere",
      },
      {
        id: "53-merkez",
        name: "Merkez",
      },
      {
        id: "53-pazar",
        name: "Pazar",
      },
    ],
  },
  {
    id: "54",
    code: "54",
    name: "Sakarya",
    districts: [
      {
        id: "54-adapazari",
        name: "Adapazarı",
      },
      {
        id: "54-akyazi",
        name: "Akyazı",
      },
      {
        id: "54-arifiye",
        name: "Arifiye",
      },
      {
        id: "54-erenler",
        name: "Erenler",
      },
      {
        id: "54-ferizli",
        name: "Ferizli",
      },
      {
        id: "54-geyve",
        name: "Geyve",
      },
      {
        id: "54-hendek",
        name: "Hendek",
      },
      {
        id: "54-karapurcek",
        name: "Karapürçek",
      },
      {
        id: "54-karasu",
        name: "Karasu",
      },
      {
        id: "54-kaynarca",
        name: "Kaynarca",
      },
      {
        id: "54-kocaali",
        name: "Kocaali",
      },
      {
        id: "54-pamukova",
        name: "Pamukova",
      },
      {
        id: "54-sapanca",
        name: "Sapanca",
      },
      {
        id: "54-serdivan",
        name: "Serdivan",
      },
      {
        id: "54-sogutlu",
        name: "Söğütlü",
      },
      {
        id: "54-tarakli",
        name: "Taraklı",
      },
    ],
  },
  {
    id: "55",
    code: "55",
    name: "Samsun",
    districts: [
      {
        id: "55-19-mayis",
        name: "19 Mayıs",
      },
      {
        id: "55-alacam",
        name: "Alaçam",
      },
      {
        id: "55-asarcik",
        name: "Asarcık",
      },
      {
        id: "55-atakum",
        name: "Atakum",
      },
      {
        id: "55-ayvacik",
        name: "Ayvacık",
      },
      {
        id: "55-bafra",
        name: "Bafra",
      },
      {
        id: "55-canik",
        name: "Canik",
      },
      {
        id: "55-carsamba",
        name: "Çarşamba",
      },
      {
        id: "55-havza",
        name: "Havza",
      },
      {
        id: "55-i-lkadim",
        name: "İlkadım",
      },
      {
        id: "55-kavak",
        name: "Kavak",
      },
      {
        id: "55-ladik",
        name: "Ladik",
      },
      {
        id: "55-salipazari",
        name: "Salıpazarı",
      },
      {
        id: "55-tekkekoy",
        name: "Tekkeköy",
      },
      {
        id: "55-terme",
        name: "Terme",
      },
      {
        id: "55-vezirkopru",
        name: "Vezirköprü",
      },
      {
        id: "55-yakakent",
        name: "Yakakent",
      },
    ],
  },
  {
    id: "56",
    code: "56",
    name: "Siirt",
    districts: [
      {
        id: "56-baykan",
        name: "Baykan",
      },
      {
        id: "56-eruh",
        name: "Eruh",
      },
      {
        id: "56-kurtalan",
        name: "Kurtalan",
      },
      {
        id: "56-merkez",
        name: "Merkez",
      },
      {
        id: "56-pervari",
        name: "Pervari",
      },
      {
        id: "56-sirvan",
        name: "Şirvan",
      },
      {
        id: "56-tillo",
        name: "Tillo",
      },
    ],
  },
  {
    id: "57",
    code: "57",
    name: "Sinop",
    districts: [
      {
        id: "57-ayancik",
        name: "Ayancık",
      },
      {
        id: "57-boyabat",
        name: "Boyabat",
      },
      {
        id: "57-dikmen",
        name: "Dikmen",
      },
      {
        id: "57-duragan",
        name: "Durağan",
      },
      {
        id: "57-erfelek",
        name: "Erfelek",
      },
      {
        id: "57-gerze",
        name: "Gerze",
      },
      {
        id: "57-merkez",
        name: "Merkez",
      },
      {
        id: "57-sarayduzu",
        name: "Saraydüzü",
      },
      {
        id: "57-turkeli",
        name: "Türkeli",
      },
    ],
  },
  {
    id: "58",
    code: "58",
    name: "Sivas",
    districts: [
      {
        id: "58-akincilar",
        name: "Akıncılar",
      },
      {
        id: "58-altinyayla",
        name: "Altınyayla",
      },
      {
        id: "58-divrigi",
        name: "Divriği",
      },
      {
        id: "58-dogansar",
        name: "Doğanşar",
      },
      {
        id: "58-gemerek",
        name: "Gemerek",
      },
      {
        id: "58-golova",
        name: "Gölova",
      },
      {
        id: "58-gurun",
        name: "Gürün",
      },
      {
        id: "58-hafik",
        name: "Hafik",
      },
      {
        id: "58-i-mranli",
        name: "İmranlı",
      },
      {
        id: "58-kangal",
        name: "Kangal",
      },
      {
        id: "58-koyulhisar",
        name: "Koyulhisar",
      },
      {
        id: "58-merkez",
        name: "Merkez",
      },
      {
        id: "58-susehri",
        name: "Suşehri",
      },
      {
        id: "58-sarkisla",
        name: "Şarkışla",
      },
      {
        id: "58-ulas",
        name: "Ulaş",
      },
      {
        id: "58-yildizeli",
        name: "Yıldızeli",
      },
      {
        id: "58-zara",
        name: "Zara",
      },
    ],
  },
  {
    id: "63",
    code: "63",
    name: "Şanlıurfa",
    districts: [
      {
        id: "63-akcakale",
        name: "Akçakale",
      },
      {
        id: "63-birecik",
        name: "Birecik",
      },
      {
        id: "63-bozova",
        name: "Bozova",
      },
      {
        id: "63-ceylanpinar",
        name: "Ceylanpınar",
      },
      {
        id: "63-eyyubiye",
        name: "Eyyübiye",
      },
      {
        id: "63-halfeti",
        name: "Halfeti",
      },
      {
        id: "63-haliliye",
        name: "Haliliye",
      },
      {
        id: "63-harran",
        name: "Harran",
      },
      {
        id: "63-hilvan",
        name: "Hilvan",
      },
      {
        id: "63-karakopru",
        name: "Karaköprü",
      },
      {
        id: "63-siverek",
        name: "Siverek",
      },
      {
        id: "63-suruc",
        name: "Suruç",
      },
      {
        id: "63-viransehir",
        name: "Viranşehir",
      },
    ],
  },
  {
    id: "73",
    code: "73",
    name: "Şırnak",
    districts: [
      {
        id: "73-beytussebap",
        name: "Beytüşşebap",
      },
      {
        id: "73-cizre",
        name: "Cizre",
      },
      {
        id: "73-guclukonak",
        name: "Güçlükonak",
      },
      {
        id: "73-i-dil",
        name: "İdil",
      },
      {
        id: "73-merkez",
        name: "Merkez",
      },
      {
        id: "73-silopi",
        name: "Silopi",
      },
      {
        id: "73-uludere",
        name: "Uludere",
      },
    ],
  },
  {
    id: "59",
    code: "59",
    name: "Tekirdağ",
    districts: [
      {
        id: "59-cerkezkoy",
        name: "Çerkezköy",
      },
      {
        id: "59-corlu",
        name: "Çorlu",
      },
      {
        id: "59-ergene",
        name: "Ergene",
      },
      {
        id: "59-hayrabolu",
        name: "Hayrabolu",
      },
      {
        id: "59-kapakli",
        name: "Kapaklı",
      },
      {
        id: "59-malkara",
        name: "Malkara",
      },
      {
        id: "59-marmaraereglisi",
        name: "Marmaraereğlisi",
      },
      {
        id: "59-muratli",
        name: "Muratlı",
      },
      {
        id: "59-saray",
        name: "Saray",
      },
      {
        id: "59-suleymanpasa",
        name: "Süleymanpaşa",
      },
      {
        id: "59-sarkoy",
        name: "Şarköy",
      },
    ],
  },
  {
    id: "60",
    code: "60",
    name: "Tokat",
    districts: [
      {
        id: "60-almus",
        name: "Almus",
      },
      {
        id: "60-artova",
        name: "Artova",
      },
      {
        id: "60-basciftlik",
        name: "Başçiftlik",
      },
      {
        id: "60-erbaa",
        name: "Erbaa",
      },
      {
        id: "60-merkez",
        name: "Merkez",
      },
      {
        id: "60-niksar",
        name: "Niksar",
      },
      {
        id: "60-pazar",
        name: "Pazar",
      },
      {
        id: "60-resadiye",
        name: "Reşadiye",
      },
      {
        id: "60-sulusaray",
        name: "Sulusaray",
      },
      {
        id: "60-turhal",
        name: "Turhal",
      },
      {
        id: "60-yesilyurt",
        name: "Yeşilyurt",
      },
      {
        id: "60-zile",
        name: "Zile",
      },
    ],
  },
  {
    id: "61",
    code: "61",
    name: "Trabzon",
    districts: [
      {
        id: "61-akcaabat",
        name: "Akçaabat",
      },
      {
        id: "61-arakli",
        name: "Araklı",
      },
      {
        id: "61-arsin",
        name: "Arsin",
      },
      {
        id: "61-besikduzu",
        name: "Beşikdüzü",
      },
      {
        id: "61-carsibasi",
        name: "Çarşıbaşı",
      },
      {
        id: "61-caykara",
        name: "Çaykara",
      },
      {
        id: "61-dernekpazari",
        name: "Dernekpazarı",
      },
      {
        id: "61-duzkoy",
        name: "Düzköy",
      },
      {
        id: "61-hayrat",
        name: "Hayrat",
      },
      {
        id: "61-koprubasi",
        name: "Köprübaşı",
      },
      {
        id: "61-macka",
        name: "Maçka",
      },
      {
        id: "61-of",
        name: "Of",
      },
      {
        id: "61-ortahisar",
        name: "Ortahisar",
      },
      {
        id: "61-surmene",
        name: "Sürmene",
      },
      {
        id: "61-salpazari",
        name: "Şalpazarı",
      },
      {
        id: "61-tonya",
        name: "Tonya",
      },
      {
        id: "61-vakfikebir",
        name: "Vakfıkebir",
      },
      {
        id: "61-yomra",
        name: "Yomra",
      },
    ],
  },
  {
    id: "62",
    code: "62",
    name: "Tunceli",
    districts: [
      {
        id: "62-cemisgezek",
        name: "Çemişgezek",
      },
      {
        id: "62-hozat",
        name: "Hozat",
      },
      {
        id: "62-mazgirt",
        name: "Mazgirt",
      },
      {
        id: "62-merkez",
        name: "Merkez",
      },
      {
        id: "62-nazimiye",
        name: "Nazımiye",
      },
      {
        id: "62-ovacik",
        name: "Ovacık",
      },
      {
        id: "62-pertek",
        name: "Pertek",
      },
      {
        id: "62-pulumur",
        name: "Pülümür",
      },
    ],
  },
  {
    id: "64",
    code: "64",
    name: "Uşak",
    districts: [
      {
        id: "64-banaz",
        name: "Banaz",
      },
      {
        id: "64-esme",
        name: "Eşme",
      },
      {
        id: "64-karahalli",
        name: "Karahallı",
      },
      {
        id: "64-merkez",
        name: "Merkez",
      },
      {
        id: "64-sivasli",
        name: "Sivaslı",
      },
      {
        id: "64-ulubey",
        name: "Ulubey",
      },
    ],
  },
  {
    id: "65",
    code: "65",
    name: "Van",
    districts: [
      {
        id: "65-bahcesaray",
        name: "Bahçesaray",
      },
      {
        id: "65-baskale",
        name: "Başkale",
      },
      {
        id: "65-caldiran",
        name: "Çaldıran",
      },
      {
        id: "65-catak",
        name: "Çatak",
      },
      {
        id: "65-edremit",
        name: "Edremit",
      },
      {
        id: "65-ercis",
        name: "Erciş",
      },
      {
        id: "65-gevas",
        name: "Gevaş",
      },
      {
        id: "65-gurpinar",
        name: "Gürpınar",
      },
      {
        id: "65-i-pekyolu",
        name: "İpekyolu",
      },
      {
        id: "65-muradiye",
        name: "Muradiye",
      },
      {
        id: "65-ozalp",
        name: "Özalp",
      },
      {
        id: "65-saray",
        name: "Saray",
      },
      {
        id: "65-tusba",
        name: "Tuşba",
      },
    ],
  },
  {
    id: "77",
    code: "77",
    name: "Yalova",
    districts: [
      {
        id: "77-altinova",
        name: "Altınova",
      },
      {
        id: "77-armutlu",
        name: "Armutlu",
      },
      {
        id: "77-cinarcik",
        name: "Çınarcık",
      },
      {
        id: "77-ciftlikkoy",
        name: "Çiftlikköy",
      },
      {
        id: "77-merkez",
        name: "Merkez",
      },
      {
        id: "77-termal",
        name: "Termal",
      },
    ],
  },
  {
    id: "66",
    code: "66",
    name: "Yozgat",
    districts: [
      {
        id: "66-akdagmadeni",
        name: "Akdağmadeni",
      },
      {
        id: "66-aydincik",
        name: "Aydıncık",
      },
      {
        id: "66-bogazliyan",
        name: "Boğazlıyan",
      },
      {
        id: "66-candir",
        name: "Çandır",
      },
      {
        id: "66-cayiralan",
        name: "Çayıralan",
      },
      {
        id: "66-cekerek",
        name: "Çekerek",
      },
      {
        id: "66-kadisehri",
        name: "Kadışehri",
      },
      {
        id: "66-merkez",
        name: "Merkez",
      },
      {
        id: "66-saraykent",
        name: "Saraykent",
      },
      {
        id: "66-sarikaya",
        name: "Sarıkaya",
      },
      {
        id: "66-sorgun",
        name: "Sorgun",
      },
      {
        id: "66-sefaatli",
        name: "Şefaatli",
      },
      {
        id: "66-yenifakili",
        name: "Yenifakılı",
      },
      {
        id: "66-yerkoy",
        name: "Yerköy",
      },
    ],
  },
  {
    id: "67",
    code: "67",
    name: "Zonguldak",
    districts: [
      {
        id: "67-alapli",
        name: "Alaplı",
      },
      {
        id: "67-caycuma",
        name: "Çaycuma",
      },
      {
        id: "67-devrek",
        name: "Devrek",
      },
      {
        id: "67-eregli",
        name: "Ereğli",
      },
      {
        id: "67-gokcebey",
        name: "Gökçebey",
      },
      {
        id: "67-kilimli",
        name: "Kilimli",
      },
      {
        id: "67-kozlu",
        name: "Kozlu",
      },
      {
        id: "67-merkez",
        name: "Merkez",
      },
    ],
  },
] as const;
